[WIP] User creation
CraftAcademy/slowfood_api_march_21 pull request #4
Opened 2021-04-29 07:27 UTC by lukeperrin10

**Current status**

- [X] - creation of user 

Plan moving forward: 

- [ ]  - adding validations to email and password
- [ ]  - and token based authorization

**User story**

As a restaurant API
In order to give visitors access to order functionality
I would like to be able to allow visitors to create an account

2021-04-29 19:24 UTC, tochman commented on app/models/user.rb
> +  validates_presence_of :email, :encrypted_password
Not sure if you need this

2021-04-29 19:27 UTC, LucasKnudsen commented on spec/requests/api/user_can_register_account_spec.rb
> +    end
:^ )

2021-04-29 19:40 UTC, lukeperrin10 commented on spec/requests/api/user_can_register_account_spec.rb
> +    end
Updated to 200

2021-04-29 19:48 UTC, lukeperrin10 commented on app/models/user.rb
> +  validates_presence_of :email, :encrypted_password
Removed now

2021-04-30 08:37 UTC, tochman requested changes
I miss unit specs for the user.

2021-04-30 10:14 UTC, lukeperrin10 commented
Adds unit for user registration

2021-04-30 11:19 UTC, tochman approved these changes
Okay. Looks good now

2021-04-30 11:19 UTC, merged